title: Dactyl
description:

name: "Dactyl"
permalink: pretty
author:
email:
url:

gems:
  - jekyll-assets
  - uglifier
  - sass

exclude: ["CNAME","editorconfig.txt","Gemfile","Gemfile.lock","README.md", "RAKEFILE"]

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
  js_compressor: uglifier
  css_compressor: sass
