name: "Dactyl"
author:
email:
url:
title:
description:
permalink: pretty
markdown: kramdown
highlighter: rouge

include: ['_pages']

exclude:
  - CNAME
  - editorconfig.txt
  - Gemfile
  - Gemfile.lock
  - README.md
  - RAKEFILE

plugins:
  - jekyll-assets
  - uglifier
  - sass

assets:
  dirname: assets
  baseurl: /assets/
  cache: false

sources:
  - _assets/css
  - _assets/fonts
  - _assets/images
  - _assets/js
